---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos74
    image: centos:7.4.1708
    command: "/usr/sbin/init"
    privileged: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: centos74-goss
verifier:
  name: goss
  lint:
    name: yamllint
